### ISSUE TITLE
Failed to connect: HttpError: ConnectFail // TypeError: Cannot read properties of undefined (reading 'start)

### ISSUE THREAD

**Issue by CurtisM-17** [NightrainsRbx/RobloxLsp#264]
This extension worked perfectly for me for months until recently when every time I try to connect studio to VSCode I receive the studio warning `Failed to connect: HttpError: ConnectFail - Make sure the VSCode Extension is running and hosting`, and when I view the VSCode extension host output I can see the extension throwing `TypeError: Cannot read properties of undefined (reading 'start') at notifyVisibleRanges (nightrains.robloxlsp-1.6.8\client\out\languageserver.js:231:25) at onDecorations (nightrains.robloxlsp-1.6.8\client\out\languageserver.js:246:9) at nightrains.robloxlsp-1.6.8\client\out\languageserver.js:112:9`. All of my extensions are up-to-date on studio and VSCode, and nothing I did would've changed any behavior. Is there any fix/workaround for this?

**Comment by majorpeterson8** [comment]
I just uninstall and reinstall roblox LSP. This worked for me!
