### ISSUE TITLE
Server still runs in background after closing VS Code on Linux

### ISSUE THREAD

**Issue by mkargus** [NightrainsRbx/RobloxLsp#58]
The language server continues to run in the background even after VS Code is closed or reloaded on Linux (I'm using Ubuntu 20.04.2.0 LTS and Arch Linux).

This effect doesn't seems to happen when using the original LSP extension.

Steps to reproduce:
1. Load up a Lua project and wait for the extension to load up.
2. Reload the window using `Developer: Reload Window` command or just closing the app.
3. Checking the System Monitoring to see multiple language server.
4. Repeat this cycle until the OS has no more memory available.

![hgfhfg](https://user-images.githubusercontent.com/14226603/124791813-64e7f900-df1a-11eb-9209-55a0d4b54e3a.png)

**Comment by NightrainsRbx** [comment]
I will have to test it on Linux since it seems to work correctly on Windows, I also need you to check VSCode output for Lua errors, and check if it happens with other workspaces.

**Comment by mkargus** [comment]
Windows does not have this issue.

I did see 2 errors.

Using `Open Folder` route and reloading the window gave this error in Extension Host log:
```
[2021-07-08 11:32:36.593] [exthost] [info] ExtensionService#_doActivateExtension Nightrains.robloxlsp {"startup":false,"extensionId":{"value":"Nightrains.robloxlsp","_lower":"nightrains.robloxlsp"},"activationEvent":"onLanguage:lua"}
[2021-07-08 11:32:36.593] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/frank/.vscode-insiders/extensions/nightrains.robloxlsp-0.15.9/client/out/extension
[2021-07-08 11:32:47.727] [exthost] [error] [Nightrains.robloxlsp] provider FAILED
[2021-07-08 11:32:47.727] [exthost] [error] Error: Connection got disposed.
	at Object.dispose (/home/frank/.vscode-insiders/extensions/nightrains.robloxlsp-0.15.9/client/node_modules/vscode-jsonrpc/lib/common/connection.js:1044:27)
	at Object.dispose (/home/frank/.vscode-insiders/extensions/nightrains.robloxlsp-0.15.9/client/node_modules/vscode-languageclient/lib/common/client.js:73:35)
	at /home/frank/.vscode-insiders/extensions/nightrains.robloxlsp-0.15.9/client/node_modules/vscode-languageclient/lib/common/client.js:2320:28
	at async Promise.all (index 0)
```


Using `Open Workspace` and opening a file from the 2nd folder, it launches a 2nd server but immediately breaks but remains open in the background:
```
...ightrains.robloxlsp-0.15.9/server/script/async/proto.lua:19: attempt to index a nil value (local 'line')
stack traceback:
	...ightrains.robloxlsp-0.15.9/server/script/async/proto.lua:19: in upvalue 'readProtoHead'
	...ightrains.robloxlsp-0.15.9/server/script/async/proto.lua:48: in local 'readProto'
	...ightrains.robloxlsp-0.15.9/server/script/async/proto.lua:60: in local 'f'
	[string "ID             = 1..."]:23: in function <[string "ID             = 1..."]:10>
	[C]: in function 'xpcall'
	[string "ID             = 1..."]:28: in main chunk
	[C]: in ?
stack traceback:
	...ns/nightrains.robloxlsp-0.15.9/server/script/service.lua:1090: in method 'listen'
	...s/extensions/nightrains.robloxlsp-0.15.9/server/main.lua:24: in main chunk
	[C]: in ?
```
